// ═══════════════════════════════════════════
//  Contact.js — MigrantWijzer — 6 talen
//  Gebruikt door: contact.html en digi.html
// ═══════════════════════════════════════════

const T = {
    nl: {
        badge: 'Amsterdam',
        hero_title: 'Contact',
        hero_sub: 'Anoniem. Gratis. In jouw taal.',
        safe_contact: 'Je kunt veilig en gratis contact opnemen. Je werkgever krijgt dit niet te zien.',
        safe_digid: 'Nederlandse regels zijn soms ingewikkeld. Wij helpen jou stap voor stap.',
        contact_why_title: 'Praat met iemand',
        c1: 'Hulp in meerdere talen',
        c2: 'Anoniem mogelijk',
        c3: 'Gratis hulp',
        c4: 'Snelle reactie via WhatsApp',
        contact_details_title: 'Contactgegevens',
        hours_title: '🕐 Bereikbaarheid',
        hours_weekdays: 'Maandag t/m vrijdag',
        hours_weekend: 'Weekend',
        hours_closed: 'Gesloten',
        hours_note: 'Buiten openingstijden kun je altijd een bericht sturen. We reageren de volgende werkdag.',
        open_whatsapp_btn: 'Open WhatsApp',
        call_direct: 'Bel direct',
        send_email: 'Stuur e-mail',
        back_home: '← Terug naar de homepage',
        footer: 'MigrantWijzer · Gratis hulp voor arbeidsmigranten · 2026',
        page_title: '📄 DigiD & papieren',
        situations: 'Herken jij dit?',
        what_todo: 'Wat kun je doen?',
        d1: 'DigiD werkt niet of je hebt er geen',
        d2: 'Formulieren zijn moeilijk te begrijpen',
        d3: 'Brieven van de gemeente niet begrijpen',
        d4: 'Problemen met BSN-nummer',
        da: 'Neem je paspoort of ID-kaart mee',
        db: 'Vraag hulp in jouw taal',
        dc: 'Wij leggen alles stap voor stap uit',
        video_title: '📹 Video uitleg',
        whatsapp_chat: 'WhatsApp hulp',
        call_help: 'Bel hulp',
    },
    en: {
        badge: 'Amsterdam',
        hero_title: 'Contact',
        hero_sub: 'Anonymous. Free. In your language.',
        safe_contact: 'You can contact us safely and for free. Your employer will not see this.',
        safe_digid: 'Dutch rules can be complicated. We will help you step by step.',
        contact_why_title: 'Talk to someone',
        c1: 'Help in multiple languages',
        c2: 'Anonymous if you wish',
        c3: 'Free help',
        c4: 'Fast response via WhatsApp',
        contact_details_title: 'Contact details',
        hours_title: '🕐 Availability',
        hours_weekdays: 'Monday to Friday',
        hours_weekend: 'Weekend',
        hours_closed: 'Closed',
        hours_note: 'Outside opening hours you can always send a message. We respond the next working day.',
        open_whatsapp_btn: 'Open WhatsApp',
        call_direct: 'Call directly',
        send_email: 'Send email',
        back_home: '← Back to homepage',
        footer: 'MigrantWijzer · Free help for labour migrants · 2026',
        page_title: '📄 DigiD & documents',
        situations: 'Do you recognise this?',
        what_todo: 'What can you do?',
        d1: 'DigiD does not work or you do not have one',
        d2: 'Forms are difficult to understand',
        d3: 'Letters from the municipality are unclear',
        d4: 'Problems with BSN number',
        da: 'Bring your passport or ID card',
        db: 'Ask for help in your language',
        dc: 'We will explain everything step by step',
        video_title: '📹 Video explanation',
        whatsapp_chat: 'WhatsApp help',
        call_help: 'Call for help',
    },
    pl: {
        badge: 'Amsterdam',
        hero_title: 'Kontakt',
        hero_sub: 'Anonimowo. Bezpłatnie. W Twoim języku.',
        safe_contact: 'Możesz skontaktować się z nami bezpiecznie i bezpłatnie.',
        safe_digid: 'Holenderskie przepisy mogą być skomplikowane. Pomożemy Ci krok po kroku.',
        contact_why_title: 'Porozmawiaj z kimś',
        c1: 'Pomoc w wielu językach',
        c2: 'Możliwość anonimowości',
        c3: 'Bezpłatna pomoc',
        c4: 'Szybka odpowiedź przez WhatsApp',
        contact_details_title: 'Dane kontaktowe',
        hours_title: '🕐 Dostępność',
        hours_weekdays: 'Poniedziałek – piątek',
        hours_weekend: 'Weekend',
        hours_closed: 'Zamknięte',
        hours_note: 'Poza godzinami otwarcia zawsze możesz wysłać wiadomość. Odpiszemy następnego dnia roboczego.',
        open_whatsapp_btn: 'Otwórz WhatsApp',
        call_direct: 'Zadzwoń bezpośrednio',
        send_email: 'Wyślij e-mail',
        back_home: '← Powrót do strony głównej',
        footer: 'MigrantWijzer · Bezpłatna pomoc dla pracowników migrujących · 2026',
        page_title: '📄 DigiD i dokumenty',
        situations: 'Czy rozpoznajesz to?',
        what_todo: 'Co możesz zrobić?',
        d1: 'DigiD nie działa lub nie masz go',
        d2: 'Formularze są trudne do zrozumienia',
        d3: 'Pisma z gminy są niezrozumiałe',
        d4: 'Problemy z numerem BSN',
        da: 'Weź paszport lub dowód osobisty',
        db: 'Poproś o pomoc w swoim języku',
        dc: 'Wyjaśnimy wszystko krok po kroku',
        video_title: '📹 Wyjaśnienie wideo',
        whatsapp_chat: 'Pomoc przez WhatsApp',
        call_help: 'Zadzwoń po pomoc',
        btn_legal: '⚖️ Informacje prawne →',
        btn_help: '🤝 Gdzie uzyskać pomoc? →',
    },
    ro: {
        badge: 'Amsterdam',
        hero_title: 'Contact',
        hero_sub: 'Anonim. Gratuit. În limba ta.',
        safe_contact: 'Poți lua legătura cu noi în siguranță și gratuit.',
        safe_digid: 'Regulile olandeze pot fi complicate. Te ajutăm pas cu pas.',
        contact_why_title: 'Vorbește cu cineva',
        c1: 'Ajutor în mai multe limbi',
        c2: 'Posibilitate de anonimat',
        c3: 'Ajutor gratuit',
        c4: 'Răspuns rapid prin WhatsApp',
        contact_details_title: 'Date de contact',
        hours_title: '🕐 Disponibilitate',
        hours_weekdays: 'Luni – vineri',
        hours_weekend: 'Weekend',
        hours_closed: 'Închis',
        hours_note: 'În afara orelor de program poți trimite oricând un mesaj. Răspundem în următoarea zi lucrătoare.',
        open_whatsapp_btn: 'Deschide WhatsApp',
        call_direct: 'Sună direct',
        send_email: 'Trimite e-mail',
        back_home: '← Înapoi la pagina principală',
        footer: 'MigrantWijzer · Ajutor gratuit pentru migranții de muncă · 2026',
        page_title: '📄 DigiD și documente',
        situations: 'Recunoști asta?',
        what_todo: 'Ce poți face?',
        d1: 'DigiD nu funcționează sau nu ai unul',
        d2: 'Formularele sunt greu de înțeles',
        d3: 'Scrisorile de la primărie sunt neclare',
        d4: 'Probleme cu numărul BSN',
        da: 'Adu pașaportul sau cartea de identitate',
        db: 'Cere ajutor în limba ta',
        dc: 'Îți explicăm totul pas cu pas',
        video_title: '📹 Explicație video',
        whatsapp_chat: 'Ajutor pe WhatsApp',
        call_help: 'Sună pentru ajutor',
        btn_legal: '⚖️ Informații juridice →',
        btn_help: '🤝 Unde primești ajutor? →',
    },
    tr: {
        badge: 'Amsterdam',
        hero_title: 'İletişim',
        hero_sub: 'Anonim. Ücretsiz. Kendi dilinde.',
        safe_contact: 'Bizimle güvenli ve ücretsiz iletişime geçebilirsin. İşveren bunu görmez.',
        safe_digid: 'Hollanda kuralları bazen karmaşıktır. Sana adım adım yardım ederiz.',
        contact_why_title: 'Biriyle konuş',
        c1: 'Çok dilli yardım',
        c2: 'Anonim mümkün',
        c3: 'Ücretsiz yardım',
        c4: 'WhatsApp ile hızlı yanıt',
        contact_details_title: 'İletişim bilgileri',
        hours_title: '🕐 Ulaşılabilirlik',
        hours_weekdays: 'Pazartesi – Cuma',
        hours_weekend: 'Hafta sonu',
        hours_closed: 'Kapalı',
        hours_note: 'Mesai saatleri dışında her zaman mesaj gönderebilirsin. Bir sonraki iş gününde yanıt veririz.',
        open_whatsapp_btn: 'WhatsApp\'ı aç',
        call_direct: 'Doğrudan ara',
        send_email: 'E-posta gönder',
        back_home: '← Ana sayfaya dön',
        footer: 'MigrantWijzer · Göçmen işçiler için ücretsiz yardım · 2026',
        page_title: '📄 DigiD & belgeler',
        situations: 'Bunu tanıyor musun?',
        what_todo: 'Ne yapabilirsin?',
        d1: 'DigiD çalışmıyor veya sahip değilsin',
        d2: 'Formlar anlaşılması zor',
        d3: 'Belediyeden gelen mektuplar anlaşılmıyor',
        d4: 'BSN numarası ile ilgili sorunlar',
        da: 'Pasaportunuzu veya kimlik kartınızı getirin',
        db: 'Kendi dilinde yardım iste',
        dc: 'Her şeyi adım adım açıklayacağız',
        video_title: '📹 Video açıklama',
        whatsapp_chat: 'WhatsApp yardımı',
        call_help: 'Ara',
        btn_legal: '⚖️ Hukuki bilgi →',
        btn_help: '🤝 Nerede yardım alırsın? →',
    },
    ar: {
        badge: 'أمستردام',
        hero_title: 'اتصل بنا',
        hero_sub: 'مجهول الهوية. مجاني. بلغتك.',
        safe_contact: 'يمكنك التواصل معنا بأمان ومجاناً. صاحب العمل لن يرى هذا.',
        safe_digid: 'القواعد الهولندية معقدة أحياناً. سنساعدك خطوة بخطوة.',
        contact_why_title: 'تحدث مع شخص ما',
        c1: 'مساعدة بلغات متعددة',
        c2: 'إمكانية إخفاء الهوية',
        c3: 'مساعدة مجانية',
        c4: 'رد سريع عبر واتساب',
        contact_details_title: 'بيانات الاتصال',
        hours_title: '🕐 أوقات التواصل',
        hours_weekdays: 'الاثنين – الجمعة',
        hours_weekend: 'عطلة نهاية الأسبوع',
        hours_closed: 'مغلق',
        hours_note: 'خارج ساعات العمل يمكنك دائماً إرسال رسالة. سنرد في يوم العمل التالي.',
        open_whatsapp_btn: 'افتح واتساب',
        call_direct: 'اتصل مباشرة',
        send_email: 'أرسل بريداً إلكترونياً',
        back_home: 'العودة إلى الصفحة الرئيسية →',
        footer: 'MigrantWijzer · مساعدة مجانية للعمال المهاجرين · 2026',
        page_title: '📄 DigiD والوثائق',
        situations: 'هل تتعرف على هذا؟',
        what_todo: 'ماذا يمكنك أن تفعل؟',
        d1: 'DigiD لا يعمل أو ليس لديك واحد',
        d2: 'النماذج صعبة الفهم',
        d3: 'رسائل البلدية غير مفهومة',
        d4: 'مشاكل مع رقم BSN',
        da: 'أحضر جواز سفرك أو بطاقة الهوية',
        db: 'اطلب المساعدة بلغتك',
        dc: 'سنشرح كل شيء خطوة بخطوة',
        video_title: '📹 شرح بالفيديو',
        whatsapp_chat: 'مساعدة عبر واتساب',
        call_help: 'اتصل للمساعدة',
        btn_legal: '⚖️ معلومات قانونية →',
        btn_help: '🤝 أين تحصل على المساعدة؟ →',
    }
};

let lang = localStorage.getItem('mw_lang') || 'nl';

function setLang(l) {
    lang = l;
    document.getElementById('langLabel').textContent = l.toUpperCase();
    document.getElementById('langMenu').classList.remove('open');
    ['nl','en','pl','ro','tr','ar'].forEach(x => {
        const btn = document.getElementById('btn-' + x);
        if (btn) btn.classList.toggle('active', x === l);
    });
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (T[l] && T[l][key]) el.textContent = T[l][key];
    });
    document.documentElement.lang = l;
    document.documentElement.dir = (l === 'ar') ? 'rtl' : 'ltr';
}

document.getElementById('langToggle').addEventListener('click', e => {
    e.stopPropagation();
    document.getElementById('langMenu').classList.toggle('open');
});
document.addEventListener('click', () => {
    document.getElementById('langMenu').classList.remove('open');
});

// Herstel opgeslagen taal bij laden
document.addEventListener('DOMContentLoaded', () => {
    const saved = localStorage.getItem('mw_lang');
    if (saved && saved !== 'nl') setLang(saved);
});